import tkinter as tk
class BasicGui:
    def __init__(self):
        self.rootWin = tk.Tk()
        self.rootWin.title("Connections")
        self.rootWin.geometry("750x750")
        self.button1 = tk.Button(self.rootWin, text="1")
        self.button1.grid(row=1, column=1)
        self.button2 = tk.Button(self.rootWin, text="2")
        self.button2.grid(row=1, column=2)
        self.button3 = tk.Button(self.rootWin, text="3")
        self.button3.grid(row=1, column=3)
        self.button4 = tk.Button(self.rootWin, text="2")
        self.button4.grid(row=1, column=4)
        self.button5 = tk.Button(self.rootWin, text="3")
        self.button5.grid(row=2, column=1)
        self.button6 = tk.Button(self.rootWin, text="4")
        self.button6.grid(row=2, column=2)
        self.button7 = tk.Button(self.rootWin, text="1")
        self.button7.grid(row=2, column=3)
        self.button8 = tk.Button(self.rootWin, text="4")
        self.button8.grid(row=2, column=4)
        self.button9 = tk.Button(self.rootWin, text="1")
        self.button9.grid(row=3, column=1)
        self.button10 = tk.Button(self.rootWin, text="3")
        self.button10.grid(row=3, column=2)
        self.button11 = tk.Button(self.rootWin, text="2")
        self.button11.grid(row=3, column=3)
        self.button12 = tk.Button(self.rootWin, text="1")
        self.button12.grid(row=3, column=4)
        self.button13 = tk.Button(self.rootWin, text="2")
        self.button13.grid(row=4, column=1)
        self.button14 = tk.Button(self.rootWin, text="4")
        self.button14.grid(row=4, column=2)
        self.button15 = tk.Button(self.rootWin, text="3")
        self.button15.grid(row=4, column=3)
        self.button16 = tk.Button(self.rootWin, text="4")
        self.button16.grid(row=4, column=4)

    def run(self):
        self.rootWin.mainloop()

myGui = BasicGui()
myGui.run()
