import tkinter as tk
class BasicGui:
    def __init__(self):
        self.rootWin = tk.Tk()
        self.rootWin.title("Connections")
        self.rootWin.geometry("750x750")
        self.button1 = tk.Button(self.rootWin, text="1", height=5, width=10)
        self.button1.grid(row=1, column=1)
        self.button2 = tk.Button(self.rootWin, text="2", height=5, width=10)
        self.button2.grid(row=1, column=2)
        self.button3 = tk.Button(self.rootWin, text="3", height=5, width=10)
        self.button3.grid(row=1, column=3)
        self.button4 = tk.Button(self.rootWin, text="2", height=5, width=10)
        self.button4.grid(row=1, column=4)
        self.button5 = tk.Button(self.rootWin, text="3", height=5, width=10)
        self.button5.grid(row=2, column=1)
        self.button6 = tk.Button(self.rootWin, text="4", height=5, width=10)
        self.button6.grid(row=2, column=2)
        self.button7 = tk.Button(self.rootWin, text="1", height=5, width=10)
        self.button7.grid(row=2, column=3)
        self.button8 = tk.Button(self.rootWin, text="4", height=5, width=10)
        self.button8.grid(row=2, column=4)
        self.button9 = tk.Button(self.rootWin, text="1", height=5, width=10)
        self.button9.grid(row=3, column=1)
        self.button10 = tk.Button(self.rootWin, text="3", height=5, width=10)
        self.button10.grid(row=3, column=2)
        self.button11 = tk.Button(self.rootWin, text="2", height=5, width=10)
        self.button11.grid(row=3, column=3)
        self.button12 = tk.Button(self.rootWin, text="1", height=5, width=10)
        self.button12.grid(row=3, column=4)
        self.button13 = tk.Button(self.rootWin, text="2", height=5, width=10)
        self.button13.grid(row=4, column=1)
        self.button14 = tk.Button(self.rootWin, text="4", height=5, width=10)
        self.button14.grid(row=4, column=2)
        self.button15 = tk.Button(self.rootWin, text="3", height=5, width=10)
        self.button15.grid(row=4, column=3)
        self.button16 = tk.Button(self.rootWin, text="4", height=5, width=10)
        self.button16.grid(row=4, column=4)

        self.label1 = tk.Label(self.rootWin, text="eon")
        self.label1.grid(row=1, column=1)
        self.label7 = tk.Label(self.rootWin, text="there")
        self.label7.grid(row=2, column=3)
        self.label9 = tk.Label(self.rootWin, text="net")
        self.label9.grid(row=3, column=1)
        self.label12 = tk.Label(self.rootWin, text="tow")
        self.label12.grid(row=3, column=4)

        self.label2 = tk.Label(self.rootWin, text="clean")
        self.label2.grid(row=1, column=2)
        self.label4 = tk.Label(self.rootWin, text="neat")
        self.label4.grid(row=1, column=4)
        self.label11 = tk.Label(self.rootWin, text="tidy")
        self.label11.grid(row=3, column=3)
        self.label13 = tk.Label(self.rootWin, text="trim")
        self.label13.grid(row=4, column=1)

        self.label3 = tk.Label(self.rootWin, text="ear")
        self.label3.grid(row=1, column=3)
        self.label5 = tk.Label(self.rootWin, text="kettle")
        self.label5.grid(row=2, column=1)
        self.label10 = tk.Label(self.rootWin, text="oil")
        self.label10.grid(row=3, column=2)
        self.label15 = tk.Label(self.rootWin, text="steel")
        self.label15.grid(row=4, column=3)

        self.label6 = tk.Label(self.rootWin, text="integer")
        self.label6.grid(row=2, column=2)
        self.label8 = tk.Label(self.rootWin, text="boolean")
        self.label8.grid(row=2, column=4)
        self.label14 = tk.Label(self.rootWin, text="float")
        self.label14.grid(row=4, column=2)
        self.label16 = tk.Label(self.rootWin, text="string")
        self.label16.grid(row=4, column=4)

        self.correct_label = tk.Label(self.rootWin, text="")
        self.correct_label.grid(row=5, column=2)

    def run(self):
        self.rootWin.mainloop()

myGui = BasicGui()
myGui.run()
